# Generated by Django 5.0.2 on 2024-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
