# Generated by Django 5.0.2 on 2024-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_alter_crypto_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
